### ISSUE TITLE
Readme questions

### ISSUE THREAD

**Issue by thebetterjort** [httpsOmkar/keycloak-hasura-connector#1]
image: httpsomkar/keycloak-hasura-connector:latest
    environment:
      KEYCLOAK_CLIENT_ID: nextjs
      KEYCLOAK_SERVER_URL: http://localhost:8080/auth //
      KEYCLOAK_REALM: master
      KEYCLOAK_SECRET: 6ff6bffd-21fe-486e-b183-6d68 // fake secret 

Does this look like you would expect?
I'm not sure what this repo does and I'm not sure what you mean about organizations. I have not been able to understand to get keycloak + hasura integrated. Could you explain in more details?

**Comment by httpsOmkar** [comment]
I have updated the documentation please check it out if you could not understand please let me know

**Comment by thebetterjort** [comment]
Thank you @httpsOmkar    

 const hasuraVariables = {
        'X-Hasura-Role': (tokenContent.resource_access[config.get('kcConfig.clientId')] || {roles: []}).roles.join(','),
        'X-Hasura-Realm-Role': tokenContent.realm_access.roles.join(','),
        'X-Hasura-User-Id': tokenContent.id,
        'X-Hasura-Organization-Id': organizationId,
        'X-Hasura-Sub-Groups-Id': subGroups,
};

Should this be available in Hasura or do I have to create this information within the dashboard?
create a "test" role as you have described.

**Comment by thebetterjort** [comment]
:"Authentication hook unauthorized this request","code":"access-denied"},"request":"{\"operationName\":null,\"variables\":{},\"query\":\"{\\n  author {\\n    id\\n    name\\n

Can you show the Hasura side of things ? Looks like its working but not sure how to setup stil?

**Comment by httpsOmkar** [comment]
I think you are not adding the `Authorization` header in the request. And after adding the it should be in format of the `Bearer ACCESS_TOKEN`.

Also I have added the documentation in the project

**Comment by thebetterjort** [comment]
Thank you very much! @httpsOmkar -- Now I'm trying to figure out how to pass ACCESS_TOKEN to apollo (with next.js) --- When I'm done I will document and write about it. :+1:
