### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by mshanak** [httpsOmkar/keycloak-hasura-connector#18]
hello
am trying to use this package, but it always returns unauthorized 401. I followed the documentation examples.

I noted in README you mentioned 

Environment variables
```
KEYCLOAK_USERNAME=YOUR_KEYCLOAK_USER_NAME
KEYCLOAK_PASSWORD=YOUR_KEYCLOAK_PSSWORD
KEYCLOAK_CLIENT_ID=YOUR_KEYCLOAK_CLIENT_ID
```
but I didn't any information about these environment variables in the documentation.

how to use these Environment variables? are they necessary?

**Comment by httpsOmkar** [comment]
Are you running the keycloak server?
Yes, all these are necessary. Without those, it will throw 401.
Have you already set up the keycloak server?

**Comment by mshanak** [comment]
Yes i have a running  keycloak server.

In previous environment variables, what do you mean by username and password?

Isn’t client_id and secret enough?

**Comment by httpsOmkar** [comment]
For keycloak connector following variables are required
```dotenv
KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
KEYCLOAK_SERVER_URL: ${KEYCLOAK_URL}
KEYCLOAK_REALM: ${KEYCLOAK_REALM}
KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
```

**Comment by mshanak** [comment]
I already filled these variables:
```
KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
KEYCLOAK_SERVER_URL: ${KEYCLOAK_URL}
KEYCLOAK_REALM: ${KEYCLOAK_REALM}
KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
```

but where to use these environment variables that found in README?

```
KEYCLOAK_USERNAME=YOUR_KEYCLOAK_USER_NAME
KEYCLOAK_PASSWORD=YOUR_KEYCLOAK_PSSWORD
KEYCLOAK_CLIENT_ID=YOUR_KEYCLOAK_CLIENT_ID
```

**Comment by httpsOmkar** [comment]
those was typo.
Updated readme.

**Comment by httpsOmkar** [comment]
Check for the server url maybe that is an issue it should be like `https://keycloak.site.com/auth` no extra slash
