### ISSUE TITLE
AccessToken.realm_access is an optional property but is not guarded in ./src/token.js

### ISSUE THREAD

**Issue by AndyCa** [httpsOmkar/keycloak-hasura-connector#36]
**Describe the bug**
realm_access property on accessToken is optional https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_accesstoken. realm_access is no longer included in JWT by default.

**To Reproduce**
1. Follow the setup steps detailed in https://github.com/httpsOmkar/keycloak-hasura-connector/tree/master/docs and try to use the connector to authorize a hasura query. 

**Expected behavior**
realm_access property on accessToken should be guarded with accessToken.hasRealmRole() in src/token.js. https://www.keycloak.org/keycloak-nodejs-auth-utils/token.js.html#hasRealmRole.

**Desktop (please complete the following information):**
 - OS: Windows 10 running docker images found in https://github.com/httpsOmkar/keycloak-hasura-connector/tree/master/install-manifests
 - Browser: chrome

https://lists.jboss.org/pipermail/keycloak-user/2018-July/014922.html

**Comment by httpsOmkar** [comment]
Actually if you see this https://github.com/httpsOmkar/keycloak-hasura-connector/blob/master/src/token.js#L11 it is not optional property we are getting roles from the https://github.com/httpsOmkar/keycloak-hasura-connector/blob/master/src/token.js#L18
If the app throwing the error is mostly because of the if keycloak url is localhost in container.
use ip or host there this may help you.

**Comment by AndyCa** [comment]
Thanks for getting back to me - all I meant is that 

https://github.com/httpsOmkar/keycloak-hasura-connector/blob/master/src/token.js#L11 `accessToken.content.realm_access.roles` can be undefined if you don't configure realm_access in your keycloak client. Missing this configuration the keycloak-hasura-connector threw an exception coming across since the realm_access property does not exist within accessToken.content. Configuring realm access in keycloak does resolve this but I thought

**Comment by httpsOmkar** [comment]
Thanks @AndyCa for you suggestion but I tried the keycloak connector with new keycloak 8.0.1 it is working.
Still I updated the code with guard for that code.
https://github.com/httpsOmkar/keycloak-hasura-connector/pull/37
Thanks Again
