### ISSUE TITLE
Any idea how to handle Authorization token?

### ISSUE THREAD

**Issue by thebetterjort** [httpsOmkar/keycloak-hasura-connector#5]
Do you have any idea how to get the authorization token from nextjs and use it in the headers?

**Comment by httpsOmkar** [comment]
I am working on component I will inform you as it is available.
__Preview__
https://github.com/httpsOmkar/auth-react-component/tree/dev

**Comment by httpsOmkar** [comment]
I work on this component library I think it is workable on the project you can try it
https://github.com/httpsOmkar/auth-react-component
http://httpsomkar.github.io/auth-react-component

**Comment by thebetterjort** [comment]
Thanks, can component be used server side?

**Comment by httpsOmkar** [comment]
I don't think so because the authentication is done at client end but I will still check that can if render on server

**Comment by thebetterjort** [comment]
import cookie from "js-cookie";

export const setCookie = (key, value) => {
    if (process.browser) {
        cookie.set(key, value, {
            expires: 1,
            path: "/"
        });
    }
};

export const removeCookie = key => {
    if (process.browser) {
        cookie.remove(key, {
            expires: 1
        });
    }
};

export const getCookie = (key, req) => {
    return process.browser ?
        getCookieFromBrowser(key) :
        getCookieFromServer(key, req);
};

const getCookieFromBrowser = key => {
    console.log('grabbing key from browser')
    return cookie.get(key);
};

const getCookieFromServer = (key, req) => {
    console.log('grabbing key from server')
    if (!req.headers.cookie) {
        return undefined;
    }
    const rawCookie = req.headers.cookie
        .split(";")
        .find(c => c.trim().startsWith(`${key}=`));
    if (!rawCookie) {
        return undefined;
    }
    return rawCookie.split("=")[1];


Something like this might work

**Comment by httpsOmkar** [comment]
I will add the serverside rendering support in the application soon.
