### ISSUE TITLE
Use the token sub over adding ID

### ISSUE THREAD

**Issue by Kevin-K** [httpsOmkar/keycloak-hasura-connector#8]
I noticed in your setup steps you add a mapper to put the user's ID in the token to populate the `X-Hasura-User-Id`  [here](https://github.com/httpsOmkar/keycloak-hasura-connector/blob/c7f0710434e2dd5293057fd3cf908c0ddfcc2bcc/src/main.js#L38).

Is it possible to use the `sub` attribute of the token instead? Could simply keycloak setup process if so.

**Comment by httpsOmkar** [comment]
Hey @Kevin-K. Thanks for the suggestion. Good catch.
Will update the code and docs soon.

**Comment by httpsOmkar** [comment]
Updated over
https://github.com/httpsOmkar/keycloak-hasura-connector/tree/dev
